# defaults used for training POYO
# this file needs to be combined with a model config and a dataset config

# Paths
# data_root: "D:/Pose/Neuro Code/data/NoveltySessInfoMatFiles/linear_processed/hippo_processed" 
###### data_root: "D:/Pose/Neuro Code/data/NoveltySessInfoMatFiles/linear_processed/hippo_scrambled/"
data_root: "/content/drive/MyDrive/Colab Notebooks/POYO/rat_hippocampus/data/"

log_dir: ./logs/multi_session

# Transforms
train_transforms: []
eval_transforms: []

# Training
epochs: 100 # 1000
batch_size: 128 # 128
eval_epochs: 1  # frequency for doing validation
eval_batch_size: null  # if null, will use batch_size
seed: 42  # use to set random seed
sanity_check_validation: true  # if true, will start the run with validation 

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

# Logging
wandb:
  enable: true # false 
  entity: null
  project: poyo_hippo_benchmarking
  run_name: poyo_hippo
  log_model: false

# GPU and CPU
precision: 32
nodes: 1
gpus: 1
num_workers: 1


# Checkpointing
ckpt_path: null  # for resuming training, or loading a model during finetuning
