- selection:
  - brainset: rat_hippocampus
    sessions:
      - cicero_09012014_sessinfo
  config:
    readout:
      readout_id: linear_maze_pos
      timestamp_key: position.timestamps
      value_key: position.pos
      normalize_mean: 0.
      normalize_std: 1. # 100.
      metrics:
        - metric:
            _target_: torchmetrics.R2Score
